language: node_js
sudo: false
cache: yarn
node_js:
  - 6
  - 8
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - export PATH=$HOME/.yarn/bin:$PATH
  - sh -e /etc/init.d/xvfb start
before_script:
  - yarn global add codecov
  - lerna bootstrap
script:
  - yarn test
  - yarn lint
  - codecov
