language: node_js
sudo: false
node_js:
  - 6
env:
  - PACKAGE=stratumn-agent-client
  - PACKAGE=stratumn-agent
  - PACKAGE=stratumn-agent-ui
  - PACKAGE=mapexplorer-core
  - PACKAGE=react-mapexplorer
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm update -g
before_script:
  - npm install -g codecov
  - lerna bootstrap
script:
  - lerna run --scope $PACKAGE test:ci
  - codecov
