language: node_js
sudo: false
node_js:
  - 4
  - 6
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm update -g
before_script:
  - npm install -g lerna
  - npm install -g bower
  - npm install -g codecov
  - cd packages/mapexplorer-core && bower install && cd -
  - lerna boostrap
script:
  - lerna run test:ci
  - codecov
