export const AGENT_INFO_REQUEST = 'AGENT_INFO_REQUEST';
export const AGENT_INFO_FAILURE = 'AGENT_INFO_FAILURE';
export const AGENT_INFO_SUCCESS = 'AGENT_INFO_SUCCESS';
export const AGENT_INFO_DELETE = 'AGENT_INFO_DELETE';

export const MAP_IDS_REQUEST = 'MAP_IDS_REQUEST';
export const MAP_IDS_FAILURE = 'MAP_IDS_FAILURE';
export const MAP_IDS_SUCCESS = 'MAP_IDS_SUCCESS';

export const SEGMENT_REQUEST = 'SEGMENT_REQUEST';
export const SEGMENT_FAILURE = 'SEGMENT_FAILURE';
export const SEGMENT_SUCCESS = 'SEGMENT_SUCCESS';

export const SEGMENTS_REQUEST = 'SEGMENTS_REQUEST';
export const SEGMENTS_FAILURE = 'SEGMENTS_FAILURE';
export const SEGMENTS_SUCCESS = 'SEGMENTS_SUCCESS';

export const CREATE_MAP_DIALOG_OPEN = 'CREATE_MAP_DIALOG_OPEN';
export const CREATE_MAP_DIALOG_CLOSE = 'CREATE_MAP_DIALOG_CLOSE';
export const CREATE_MAP_REQUEST = 'CREATE_MAP_REQUEST';
export const CREATE_MAP_FAILURE = 'CREATE_MAP_FAILURE';
export const CREATE_MAP_SUCCESS = 'CREATE_MAP_SUCCESS';
export const CREATE_MAP_CLEAR = 'CREATE_MAP_CLEAR';

export const APPEND_SEGMENT_DIALOG_OPEN = 'APPEND_SEGMENT_DIALOG_OPEN';
export const APPEND_SEGMENT_DIALOG_SELECT_ACTION =
  'APPEND_SEGMENT_DIALOG_SELECT_ACTION';
export const APPEND_SEGMENT_DIALOG_CLOSE = 'APPEND_SEGMENT_DIALOG_CLOSE';
export const APPEND_SEGMENT_REQUEST = 'APPEND_SEGMENT_REQUEST';
export const APPEND_SEGMENT_FAILURE = 'APPEND_SEGMENT_FAILURE';
export const APPEND_SEGMENT_SUCCESS = 'APPEND_SEGMENT_SUCCESS';
export const APPEND_SEGMENT_CLEAR = 'APPEND_SEGMENT_CLEAR';

export const MAP_EXPLORER_SELECT_SEGMENT = 'MAP_EXPLORER_SELECT_SEGMENT';
export const MAP_EXPLORER_CLEAR_SEGMENT = 'MAP_EXPLORER_CLEAR_SEGMENT';

export const SELECT_REFS_DIALOG_CLOSE = 'SELECT_REFS_DIALOG_CLOSE';
export const SELECT_REFS_DIALOG_OPEN = 'SELECT_REFS_DIALOG_OPEN';
export const SELECT_REFS_ADD = 'SELECT_REFS_ADD';
export const SELECT_REFS_REMOVE = 'SELECT_REFS_REMOVE';
export const SELECT_REFS_CLEAR = 'SELECT_REFS_CLEAR';
