export const AGENT_INFO_SUCCESS = 'AGENT_INFO_SUCCESS';
export const AGENT_INFO_FAILURE = 'AGENT_INFO_FAILURE';
export const MAP_IDS_SUCCESS = 'MAP_IDS_SUCCESS';
export const MAP_IDS_FAILURE = 'MAP_IDS_FAILURE';
export const FIND_SEGMENTS_SUCCESS = 'FIND_SEGMENTS_SUCCESS';
export const FIND_SEGMENTS_FAILURE = 'FIND_SEGMENTS_FAILURE';
