export const AGENT_INFO_REQUEST = 'AGENT_INFO_REQUEST';
export const AGENT_INFO_FAILURE = 'AGENT_INFO_FAILURE';
export const AGENT_INFO_SUCCESS = 'AGENT_INFO_SUCCESS';

export const MAP_IDS_REQUEST = 'MAP_IDS_REQUEST';
export const MAP_IDS_FAILURE = 'MAP_IDS_FAILURE';
export const MAP_IDS_SUCCESS = 'MAP_IDS_SUCCESS';

export const SEGMENTS_REQUEST = 'SEGMENTS_REQUEST';
export const SEGMENTS_FAILURE = 'SEGMENTS_FAILURE';
export const SEGMENTS_SUCCESS = 'SEGMENTS_SUCCESS';

export const CREATE_MAP_DIALOG_OPEN = 'CREATE_MAP_DIALOG_OPEN';
export const CREATE_MAP_DIALOG_CLOSE = 'CREATE_MAP_DIALOG_CLOSE';
export const CREATE_MAP_REQUEST = 'CREATE_MAP_REQUEST';
export const CREATE_MAP_FAILURE = 'CREATE_MAP_FAILURE';
export const CREATE_MAP_SUCCESS = 'CREATE_MAP_SUCCESS';
export const CREATE_MAP_CLEAR = 'CREATE_MAP_CLEAR';
