language: node_js
sudo: false
node_js:
  - 0.12
  - 4
  - 5
  - 6
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm update -g
before_script:
  - npm install -g bower
  - bower install
script:
  - npm run test:ci
